runtime: go
api_version: go1
application: mtp-present
version: 1

handlers:
- url: /static
  static_dir: present/static
  application_readable: true

- url: /.*
  script: _go_app

nobuild_files: ^201[0-9]/
